In [1]:
print('hello world')

hello world

### Datasets:

Here's one dataset for food prices https://www.kaggle.com/jboysen/global-food-prices

Here is the dataset for temperature and rainfalls http://sdwebx.worldbank.org/climateportal/index.cfm?page=downscaled_data_download&menu=historical

### Hypothesis: 

Do changes in average temperature and average level of rainfall affect the change in the average price on X crop in X country in X-X years

### Questions to the Professor:

1. How can we all access and work simultaneously in the shared Github repo (with 1 master and 3 collaborators)?

In [1]:
import pandas as pd

pricesdata='https://raw.githubusercontent.com/vzakhozhyi/599-A-Final-Project/master/Data/wfp_market_food_prices.csv'
prices = pd.read_csv(pricesdata,header=0, encoding = 'ISO-8859-1')

TLdata="https://github.com/vzakhozhyi/599-A-Final-Project/raw/master/Data/Temp1991_2015.xls"
TL=pd.read_excel(TLdata)

RFdata="https://github.com/vzakhozhyi/599-A-Final-Project/raw/master/Data/RainFall1991_2015.xls"
RF=pd.read_excel(RFdata)

In [2]:
prices.shape

(743914, 18)

In [3]:
prices.head(10)
prices.tail(10)

,adm0_id,adm0_name,adm1_id,adm1_name,mkt_id,mkt_name,cm_id,cm_name,cur_id,cur_name,pt_id,pt_name,um_id,um_name,mp_month,mp_year,mp_price,mp_commoditysource
743904,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,156,Sesame,83,SSP,15,Retail,47,3.5 KG,5,2016,115.0,WFP
743905,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,156,Sesame,83,SSP,15,Retail,47,3.5 KG,7,2016,100.0,WFP
743906,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,156,Sesame,83,SSP,15,Retail,47,3.5 KG,2,2017,425.0,WFP
743907,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,156,Sesame,83,SSP,15,Retail,47,3.5 KG,3,2017,443.0,WFP
743908,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,156,Sesame,83,SSP,15,Retail,47,3.5 KG,4,2017,425.0,WFP
743909,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,156,Sesame,83,SSP,15,Retail,47,3.5 KG,5,2017,400.0,WFP
743910,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,284,Fuel (diesel),83,SSP,15,Retail,15,L,2,2017,12.5,WFP
743911,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,284,Fuel (diesel),83,SSP,15,Retail,15,L,3,2017,95.0,WFP
743912,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,285,Fuel (petrol-gasoline),83,SSP,15,Retail,15,L,2,2017,95.0,WFP
743913,70001,South Sudan,2750,Eastern Equatoria,1786,Torit,285,Fuel (petrol-gasoline),83,SSP,15,Retail,15,L,3,2017,93.7,WFP

In [8]:
prices.dtypes

adm0_id                 int64
adm0_name              object
adm1_id                 int64
adm1_name              object
mkt_id                  int64
mkt_name               object
cm_id                   int64
cm_name                object
cur_id                  int64
cur_name               object
pt_id                   int64
pt_name                object
um_id                   int64
um_name                object
mp_month                int64
mp_year                 int64
mp_price              float64
mp_commoditysource     object
dtype: object